# Header
menu:
  技術文章: /categories/技術文章/
  文章一覽: /archives/

# SubNav
subnav:
  facebook: https://www.facebook.com/yang.hong.xin
  linkedin: https://www.linkedin.com/in/hongxin-yang/
  github: https://github.com/jk195417
  mail: mailto:jk195417@gmail.com
  rss: /atom.xml
  # weibo: "#"
  # zhihu: "#"
  # qq: "#"
  # weixin: "#"
  # jianshu: "#"
  # douban: "#"
  # segmentfault: "#"
  # bilibili: "#"
  # acfun: "#"
  # google: "#"
  # twitter: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
url: https://blog.yang-hong-xin.com/
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: 展開以顯示全文
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: 顯示全文
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: 謝謝你的支持
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay:
# 微信二维码图片地址
weixin:

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: 沒有目錄

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics:
google_analytics: UA-117837845-1
favicon: images/favicon.png

#你的头像url
avatar: https://i.imgur.com/Ulq9USl.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: yang-hong-xin

#5、Gitment
gitment_owner: false #你的 GitHub ID
gitment_repo: #存储评论的 repo
gitment_oauth:
  client_id: #client ID
  client_secret: #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: "#337CA0"
  # 右滑板块背景
  slider: linear-gradient(200deg,#136d9a,#a0cfe4,#136d9a,#e8c37e)

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 搜尋文章
  aboutme: 關於我
  friends: false

friends:
  友情链接1: http://localhost:4000/
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

aboutme: |
  <div>
    Web Developer，高雄人
    <br>
    <br>
    <h1>技能</h1>
    <ul>
      <li>Ruby</li>
      <li>Ruby on Rails</li>
      <li>Git</li>
      <li>JavaScript</li>
    </ul>
    <br>
    <h1>學歷</h1>
    <ul>
      <li>中山大學 資管所 2017 - </li>
      <li>逢甲大學 自控系 2013 - 2017</li>
      <li>高雄中學 2010 - 2013</li>
    </ul>
  </div>
